from prism.diff.filter import filter_diff
from prism.diff.source import ChangedFile


def _cf(path: str, patch: str = "+code\n") -> ChangedFile:
    return ChangedFile(path=path, patch=patch, added=1, removed=0)


def test_lock_files_are_skipped() -> None:
    result = filter_diff([_cf("package-lock.json"), _cf("go.sum"), _cf("src/app.py")])
    assert [f.path for f in result.kept] == ["src/app.py"]
    skipped_paths = {p for p, _ in result.skipped}
    assert skipped_paths == {"package-lock.json", "go.sum"}


def test_minified_and_map_extensions_skipped() -> None:
    result = filter_diff([_cf("a.min.js"), _cf("b.bundle.js"), _cf("c.css.map"), _cf("keep.ts")])
    assert [f.path for f in result.kept] == ["keep.ts"]


def test_generated_marker_is_skipped() -> None:
    gen = "diff --git a/g.ts b/g.ts\n+// @generated by tool\n+const x = 1\n"
    result = filter_diff([_cf("g.ts", patch=gen)])
    assert result.kept == []
    assert result.skipped[0][0] == "g.ts"


def test_migration_is_kept_even_when_generated() -> None:
    gen = "diff --git a/m.sql b/m.sql\n+-- @generated\n+ALTER TABLE x ADD COLUMN y int;\n"
    result = filter_diff([_cf("db/migrations/001_add_col.sql", patch=gen)])
    assert [f.path for f in result.kept] == ["db/migrations/001_add_col.sql"]
    assert result.skipped == []


def test_skipped_entries_carry_a_reason() -> None:
    result = filter_diff([_cf("yarn.lock")])
    assert result.kept == []
    path, reason = result.skipped[0]
    assert path == "yarn.lock"
    assert reason  # non-empty human-readable reason (no silent truncation)


def test_normal_source_file_is_kept() -> None:
    result = filter_diff([_cf("src/prism/cli.py")])
    assert [f.path for f in result.kept] == ["src/prism/cli.py"]
    assert result.skipped == []
